apiVersion: apps/v1
kind: Deployment
metadata:
  name: developeriq-deployment-dev
  labels:
    app: developeriq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: developeriq
  template:
    metadata:
      labels:
        app: developeriq
        role: rolling-update
    spec:
      containers:
      - name: developeriq
        image: dylnesh/deviqfront:1.0 
        ports:
        - containerPort: 5000  
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: developeriq
  name: developeriq-service-dev
spec:
  ports:
  - port: 5000  
    protocol: TCP
    targetPort: 5000  
  selector:
    app: developeriq
  type: LoadBalancer

  ---

  ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion-deployment-dev
  labels:
    app: data-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
        role: ingestion-update
    spec:
      containers:
      - name: data-ingestion
        image: dylnesh/deviqingest:1.0  
        ports:
        - containerPort: 6000  

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: data-ingestion
  name: data-ingestion-service-dev
spec:
  ports:
  - port: 6000  
    protocol: TCP
    targetPort: 6000  
  selector:
    app: data-ingestion
  type: LoadBalancer

