apiVersion: apps/v1
kind: Deployment
metadata:
  name: developeriq-dataingestion-prod
  labels:
    app: developeriqdata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: developeriqdata
  template:
    metadata:
      labels:
        app: developeriqdata
        role: rolling-update
    spec:
      containers:
      - name: developeriqdata
        image: dylnesh/deviqingest:1.0 
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: developeriq-deployment-prod
  labels:
    app: developeriq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: developeriq
  template:
    metadata:
      labels:
        app: developeriq
        role: rolling-update
    spec:
      containers:
      - name: developeriq
        image: dylnesh/deviqfront:1.0 
        ports:
        - containerPort: 5000  
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: developeriq
  name: developeriq-service-prod
spec:
  ports:
  - port: 5000  
    protocol: TCP
    targetPort: 5000  
  selector:
    app: developeriq
  type: LoadBalancer
