apiVersion: apps/v1
kind: Deployment
metadata:
  name: developeriq-deployment-dev
  labels:
    app: developeriq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: developeriq
  template:
    metadata:
      labels:
        app: developeriq
        role: rolling-update
    spec:
      containers:
      - name: developeriq
        image: dylnesh/deviqimg:1.0 
        ports:
        - containerPort: 5000  
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: developeriq
  name: developeriq-service-dev
spec:
  ports:
  - port: 5000  
    protocol: TCP
    targetPort: 5000  
  selector:
    app: developeriq
  type: LoadBalancer
